version: "3.8"

services:
  aimx_eval_tensorflow_cnn:
    build:
      context: .
    environment:
      APP_ENV: local
      MLFLOW_TRACKING_URI: http://host.docker.internal:8081
      MODEL_WIGHTS_PATH: ./weights/vgg16_model.h5  # or xception_model.h5
      DATASET_PATH: ./datasets/test.zip
      EXPERIMENT_NAME: ResNet-Image-Classification-onnx
    volumes:
      - python_cache:/root/.cache/pip
    ports:
      - 3910:3910

volumes:
  python_cache:
