apiVersion: v1
kind: Service
metadata:
  name: evaluation-worker
  namespace: internal-aimx
spec:
  selector:
    app: evaluation-worker
  ports:
    - protocol: TCP
      port: 3800
      targetPort: 3800
  type: ClusterIP
