apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  namespace: internal-aimx
spec:
  volumeName: shared-data-pv  # <--- force binding
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
